### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by Emiska** [robkorn/plutus-experimental-smart-contracts#2]
Line 14, Column 53:

 error:
    • Not in scope: data constructor ‘PendingTx'’
      Perhaps you meant one of these:
        ‘PendingTx’ (imported from Ledger.Validation),
        ‘PendingTxIn’ (imported from Ledger.Validation),
        ‘PendingTxOut’ (imported from Ledger.Validation)
    • In the Template Haskell quotation
        [|| \ (submittedPIN :: Int) (myPIN :: Int) (p ::  'PendingTx')
              -> if submittedPIN == myPIN then
                     ()
                 else
                     $$(P.error)
                       ($$(P.traceH)
                          "Please supply the correct PIN number to withdraw ada." ()) ||]
      In the typed splice:
        $$(PlutusTx.compile
             [|| \ (submittedPIN :: Int) (myPIN :: Int) (p ::  'PendingTx')
                   -> if submittedPIN == myPIN then
                          ()
                      else
                          $$(P.error)
                            ($$(P.traceH)
                               "Please supply the correct PIN number to withdraw ada." ()) ||])
   |
14 |     [|| \(submittedPIN :: Int) (myPIN :: Int) (p :: 'PendingTx') ->
   |                                                     ^^^^^^^^^^^
jump
Line 20, Column 25:

 error:
    Not in scope: type constructor or class ‘Address'’
    Perhaps you meant one of these:
      ‘Address’ (imported from Ledger),
      ‘AddressOf’ (imported from Ledger)
   |
20 | smartContractAddress :: Address'
   |                         ^^^^^^^^

**Comment by robkorn** [comment]
Hello there Emiska,

The code you are trying to run was written for the original Plutus codebase that was released right after Plutusfest 2018. In April there was a new update and there were a number of changes which breaks some of the code.

For example as stated in the first error, originally the type was `PendingTx'` but now it is `PendingTx` (without the `'`).
Same thing for the second with `Address'` and `Address`.

Simply delete the `'` and those lines specifically should work, but I can't promise everything else will go swimmingly well since if I recall correctly there is no changelog so there will likely be even more code-breaking updates too.
